version: 1
from: "infracamp/kickstart-flavor-gaia"

apache_fallback_resource: "/index.php"

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"

  run:
    - "sudo -u www-data touch /tmp/log"
    - "D:tail -f /tmp/log"

